/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const ContactSubmission = IDL.Record({
  'projectType' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : Time,
  'phone' : IDL.Opt(IDL.Text),
});
export const PortfolioItem = IDL.Record({
  'title' : IDL.Text,
  'description' : IDL.Text,
  'imageUrl' : IDL.Text,
  'category' : IDL.Text,
  'liveUrl' : IDL.Text,
});
export const Testimonial = IDL.Record({
  'clientName' : IDL.Text,
  'quote' : IDL.Text,
  'roleOrCompany' : IDL.Text,
  'rating' : IDL.Int,
});

export const idlService = IDL.Service({
  'getAllContactSubmissions' : IDL.Func(
      [],
      [IDL.Vec(ContactSubmission)],
      ['query'],
    ),
  'getAllPortfolioItems' : IDL.Func([], [IDL.Vec(PortfolioItem)], ['query']),
  'getAllTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
  'getContactSubmission' : IDL.Func([IDL.Int], [ContactSubmission], ['query']),
  'getPortfolioByCategory' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(PortfolioItem)],
      ['query'],
    ),
  'getPortfolioItem' : IDL.Func([IDL.Int], [PortfolioItem], ['query']),
  'getTestimonialsByRating' : IDL.Func(
      [IDL.Int],
      [IDL.Vec(Testimonial)],
      ['query'],
    ),
  'searchPortfolioByTitle' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(PortfolioItem)],
      ['query'],
    ),
  'submitContactForm' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Text, IDL.Text],
      [IDL.Int],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const ContactSubmission = IDL.Record({
    'projectType' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : Time,
    'phone' : IDL.Opt(IDL.Text),
  });
  const PortfolioItem = IDL.Record({
    'title' : IDL.Text,
    'description' : IDL.Text,
    'imageUrl' : IDL.Text,
    'category' : IDL.Text,
    'liveUrl' : IDL.Text,
  });
  const Testimonial = IDL.Record({
    'clientName' : IDL.Text,
    'quote' : IDL.Text,
    'roleOrCompany' : IDL.Text,
    'rating' : IDL.Int,
  });
  
  return IDL.Service({
    'getAllContactSubmissions' : IDL.Func(
        [],
        [IDL.Vec(ContactSubmission)],
        ['query'],
      ),
    'getAllPortfolioItems' : IDL.Func([], [IDL.Vec(PortfolioItem)], ['query']),
    'getAllTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
    'getContactSubmission' : IDL.Func(
        [IDL.Int],
        [ContactSubmission],
        ['query'],
      ),
    'getPortfolioByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(PortfolioItem)],
        ['query'],
      ),
    'getPortfolioItem' : IDL.Func([IDL.Int], [PortfolioItem], ['query']),
    'getTestimonialsByRating' : IDL.Func(
        [IDL.Int],
        [IDL.Vec(Testimonial)],
        ['query'],
      ),
    'searchPortfolioByTitle' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(PortfolioItem)],
        ['query'],
      ),
    'submitContactForm' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Text, IDL.Text],
        [IDL.Int],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };